export const experiences = [
  { name: "ReactJS" },
  { name: "Angular2" },
  { name: "Java" },
  { name: "Springboot" },
  { name: "Javascript" },
  { name: "Typescript" },
  { name: "Node" },
  { name: "HTML5" },
  { name: "CSS" },
  { name: "Git" },
  { name: "SQLServer" },
  { name: "DynamoDB" },
  { name: "Redis" },
];
